### ISSUE TITLE
Authentication system

### ISSUE THREAD

**Issue by SiongSng** [Lipoic/Lipoic-Server#12]

**Comment by xiaoxigua-1** [comment]
# TODO
- [ ] `/api/user/sign-up`
- [ ] `/api/authentication/fb?<code>`
- [ ] `/api/authentication/fb/url?<oauth_redirect_uri>`
